; generated by ferret llvm backend

%local__main__Point = type { i32, i32 }

define i32 @main__run() {
entry:
  %x_alloca = alloca i32, align 4
  %_t1_alloca = alloca i8, align 1
  %_t2_alloca = alloca i8, align 1
  %_asgn1 = or i32 0, 0
  store i32 %_asgn1, ptr %x_alloca
  br label %bb1
bb1:
  %_ld3 = load i32, ptr %x_alloca
  %_cmp4 = icmp slt i32 %_ld3, 10
  %_asgn2 = zext i1 %_cmp4 to i8
  store i8 %_asgn2, ptr %_t1_alloca
  %_ld5 = load i8, ptr %_t1_alloca
  %_br6 = icmp ne i8 %_ld5, 0
  br i1 %_br6, label %bb2, label %bb3
bb2:
  %_ld8 = load i32, ptr %x_alloca
  %_asgn7 = add i32 %_ld8, 1
  store i32 %_asgn7, ptr %x_alloca
  %_ld10 = load i32, ptr %x_alloca
  %_cmp11 = icmp eq i32 %_ld10, 5
  %_asgn9 = zext i1 %_cmp11 to i8
  store i8 %_asgn9, ptr %_t2_alloca
  %_ld12 = load i8, ptr %_t2_alloca
  %_br13 = icmp ne i8 %_ld12, 0
  br i1 %_br13, label %bb4, label %bb5
bb3:
  %_ld14 = load i32, ptr %x_alloca
  ret i32 %_ld14
bb4:
  br label %bb3
bb5:
  br label %bb6
bb6:
  br label %bb1
}

define void @main__nothing(ptr byval(%local__main__Point) align 4 %p, i32 %a) {
entry:
  %a_alloca = alloca i32, align 4
  br label %bb1
bb1:
  unreachable
}

define i32 @main__main() {
entry:
  %num1_alloca = alloca i32, align 4
  %num2_alloca = alloca i8, align 1
  %boolean_alloca = alloca i8, align 1
  %val_alloca = alloca i32, align 4
  %_t7_alloca = alloca i8, align 1
  %_t9_alloca = alloca i32, align 4
  %p = alloca %local__math__vec2__Vec2, align 4
  %point = alloca %local__main__Point, align 4
  %_t6 = alloca %local__math__vec2__Vec2, align 4
  %_t8 = alloca %local__math__vec2__Vec2, align 4
  %_asgn1 = or i32 0, 1023554363
  store i32 %_asgn1, ptr %num1_alloca
  %_asgn2 = trunc i32 1023554363 to i8
  store i8 %_asgn2, ptr %num2_alloca
  %_aggret3 = call %local__math__vec2__Vec2 @util__build__Origin()
  store %local__math__vec2__Vec2 %_aggret3, ptr %p
  store i32 0, ptr %_t6
  %_addr4 = getelementptr inbounds i8, ptr %_t6, i64 4
  store i32 0, ptr %_addr4
  %_cmp6 = load i32, ptr %p
  %_cmp7 = load i32, ptr %_t6
  %_cmp8 = icmp eq i32 %_cmp6, %_cmp7
  %_cmp9 = zext i1 %_cmp8 to i8
  %_addr10 = getelementptr inbounds i8, ptr %p, i64 4
  %_addr11 = getelementptr inbounds i8, ptr %_t6, i64 4
  %_cmp12 = load i32, ptr %_addr10
  %_cmp13 = load i32, ptr %_addr11
  %_cmp14 = icmp eq i32 %_cmp12, %_cmp13
  %_cmp15 = zext i1 %_cmp14 to i8
  %_cmp16 = and i8 %_cmp9, %_cmp15
  %_asgn5 = or i8 0, %_cmp16
  store i8 %_asgn5, ptr %_t7_alloca
  %_ld17 = load i8, ptr %_t7_alloca
  %_br18 = icmp ne i8 %_ld17, 0
  br i1 %_br18, label %bb1, label %bb2
bb1:
  call void @llvm.memcpy.p0.p0.i64(ptr align 4 %_t8, ptr align 4 %p, i64 8, i1 false)
  %_asgn19 = call i32 @math__vec2__Len2(ptr byval(%local__math__vec2__Vec2) align 4 %_t8)
  store i32 %_asgn19, ptr %_t9_alloca
  %_ld20 = load i32, ptr %_t9_alloca
  ret i32 %_ld20
bb2:
  br label %bb3
bb3:
  store i32 1, ptr %point
  %_addr21 = getelementptr inbounds i8, ptr %point, i64 4
  store i32 2, ptr %_addr21
  call void @main__nothing(ptr byval(%local__main__Point) align 4 %point, i32 23)
  %_asgn22 = or i8 0, 1
  store i8 %_asgn22, ptr %boolean_alloca
  %_asgn23 = call i32 @std__math__ClampToZero(i32 -34)
  store i32 %_asgn23, ptr %val_alloca
  ret i32 1
}
