package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	runtimeabi "compiler/internal/runtime/abi"
	"compiler/internal/types"
)

var nonPrimitiveKinds = []string{
	"POINTER",
	"STRUCT",
	"ARRAY",
	"SLICE",
	"MAP",
	"FUNCTION",
	"INTERFACE",
}

func main() {
	root := "."
	primitiveKinds := primitiveKindNames()
	mapKeyKinds := runtimeabi.MapKeyKinds
	primitiveSpecs := runtimeabi.PrimitiveSpecs
	intWidths := runtimeabi.IntWidths
	floatSpecs := runtimeabi.FloatSpecs
	if len(primitiveKinds) == 0 || len(nonPrimitiveKinds) == 0 || len(mapKeyKinds) == 0 {
		fail(fmt.Errorf("missing ABI kind definitions"))
	}
	if err := validatePrimitiveSpecs(primitiveSpecs); err != nil {
		fail(err)
	}
	if len(intWidths) == 0 || len(floatSpecs) == 0 {
		fail(fmt.Errorf("missing ABI numeric specs"))
	}

	values := make(map[string]uint32)
	for i, name := range primitiveKinds {
		values[name] = uint32(i)
	}
	offset := uint32(len(primitiveKinds))
	for i, name := range nonPrimitiveKinds {
		values[name] = offset + uint32(i)
	}

	if err := writeCHdr(filepath.Join(root, "runtime/core/abi_constants.h"), primitiveKinds, values, intWidths, floatSpecs); err != nil {
		fail(err)
	}
	if err := writeGo(filepath.Join(root, "internal/runtime/abi/constants.go"), primitiveKinds, values); err != nil {
		fail(err)
	}
	if err := writeTS(filepath.Join(root, "runtime/wasm/runtime_abi.ts"), primitiveKinds, values, mapKeyKinds, intWidths, floatSpecs); err != nil {
		fail(err)
	}
	if err := writePrimitiveTypesHeader(filepath.Join(root, "runtime/core/primitive_types.h"), primitiveSpecs); err != nil {
		fail(err)
	}
}

func primitiveKindNames() []string {
	out := make([]string, 0, len(types.PrimitiveTypeNames))
	for _, name := range types.PrimitiveTypeNames {
		out = append(out, abiKindName(name))
	}
	return out
}

func abiKindName(name types.TYPE_NAME) string {
	switch name {
	case types.TYPE_STRING:
		return "STRING"
	case types.TYPE_BOOL:
		return "BOOL"
	case types.TYPE_BYTE:
		return "BYTE"
	case types.TYPE_CHAR:
		return "CHAR"
	default:
		return strings.ToUpper(string(name))
	}
}

func writeCHdr(path string, primitiveKinds []string, values map[string]uint32, intWidths []int, floatSpecs []runtimeabi.FloatSpec) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by scripts/gen_abi_constants.go; DO NOT EDIT.\n")
	buf.WriteString("#ifndef FERRET_ABI_CONSTANTS_H\n")
	buf.WriteString("#define FERRET_ABI_CONSTANTS_H\n\n")
	for _, name := range primitiveKinds {
		buf.WriteString(fmt.Sprintf("#define FERRET_TYPE_KIND_%s %d\n", name, values[name]))
	}
	for _, name := range nonPrimitiveKinds {
		buf.WriteString(fmt.Sprintf("#define FERRET_TYPE_KIND_%s %d\n", name, values[name]))
	}
	buf.WriteString("\n// WASM type descriptor layout (packed u32 fields).\n")
	buf.WriteString(fmt.Sprintf("#define FERRET_TYPEDESC_KIND_OFFSET %d\n", runtimeabi.TypeDescKindOffset))
	buf.WriteString(fmt.Sprintf("#define FERRET_TYPEDESC_SIZE_OFFSET %d\n", runtimeabi.TypeDescSizeOffset))
	buf.WriteString(fmt.Sprintf("#define FERRET_TYPEDESC_INFO1_OFFSET %d\n", runtimeabi.TypeDescInfo1Offset))
	buf.WriteString(fmt.Sprintf("#define FERRET_TYPEDESC_INFO2_OFFSET %d\n", runtimeabi.TypeDescInfo2Offset))
	buf.WriteString(fmt.Sprintf("#define FERRET_TYPEDESC_SIZE %d\n", runtimeabi.TypeDescSizeBytes))
	buf.WriteString(fmt.Sprintf("#define FERRET_FIELD_INFO_OFFSET_OFFSET %d\n", runtimeabi.FieldInfoOffsetOffset))
	buf.WriteString(fmt.Sprintf("#define FERRET_FIELD_INFO_TYPE_OFFSET %d\n", runtimeabi.FieldInfoTypeOffset))
	buf.WriteString(fmt.Sprintf("#define FERRET_FIELD_INFO_SIZE %d\n", runtimeabi.FieldInfoSizeBytes))
	buf.WriteString("\n// WASM runtime layout constants.\n")
	buf.WriteString(fmt.Sprintf("#define FERRET_ARRAY_DATA_OFFSET %d\n", runtimeabi.ArrayDataOffset))
	buf.WriteString(fmt.Sprintf("#define FERRET_ARRAY_LEN_OFFSET %d\n", runtimeabi.ArrayLenOffset))
	buf.WriteString(fmt.Sprintf("#define FERRET_ARRAY_CAP_OFFSET %d\n", runtimeabi.ArrayCapOffset))
	buf.WriteString(fmt.Sprintf("#define FERRET_ARRAY_ELEM_SIZE_OFFSET %d\n", runtimeabi.ArrayElemSizeOffset))
	buf.WriteString(fmt.Sprintf("#define FERRET_ARRAY_ELEM_TYPE_OFFSET %d\n", runtimeabi.ArrayElemTypeOffset))
	buf.WriteString(fmt.Sprintf("#define FERRET_ARRAY_HEADER_SIZE %d\n", runtimeabi.ArrayHeaderSize))
	buf.WriteString(fmt.Sprintf("#define FERRET_SLICE_DATA_OFFSET %d\n", runtimeabi.SliceDataOffset))
	buf.WriteString(fmt.Sprintf("#define FERRET_SLICE_LEN_OFFSET %d\n", runtimeabi.SliceLenOffset))
	buf.WriteString(fmt.Sprintf("#define FERRET_SLICE_CAP_OFFSET %d\n", runtimeabi.SliceCapOffset))
	buf.WriteString(fmt.Sprintf("#define FERRET_SLICE_ELEM_SIZE_OFFSET %d\n", runtimeabi.SliceElemSizeOffset))
	buf.WriteString(fmt.Sprintf("#define FERRET_SLICE_ELEM_TYPE_OFFSET %d\n", runtimeabi.SliceElemTypeOffset))
	buf.WriteString(fmt.Sprintf("#define FERRET_SLICE_HEADER_SIZE %d\n", runtimeabi.SliceHeaderSize))
	buf.WriteString(fmt.Sprintf("#define FERRET_INTERFACE_DATA_OFFSET %d\n", runtimeabi.InterfaceDataOffset))
	buf.WriteString(fmt.Sprintf("#define FERRET_INTERFACE_EXTRA_OFFSET %d\n", runtimeabi.InterfaceExtraOffset))
	buf.WriteString(fmt.Sprintf("#define FERRET_INTERFACE_SIZE %d\n", runtimeabi.InterfaceSize))
	buf.WriteString(fmt.Sprintf("#define FERRET_UNION_TAG_SIZE %d\n", runtimeabi.UnionTagSize))
	buf.WriteString(fmt.Sprintf("#define FERRET_UNION_PTR_OFFSET %d\n", runtimeabi.UnionPtrOffset))
	buf.WriteString(fmt.Sprintf("#define FERRET_MAP_HANDLE_SIZE %d\n", runtimeabi.MapHandleSize))
	buf.WriteString("\n// Hash constants.\n")
	buf.WriteString(fmt.Sprintf("#define FERRET_MAP_HASH_SEED %dU\n", runtimeabi.MapHashSeed))
	buf.WriteString(fmt.Sprintf("#define FERRET_FNV_OFFSET_BASIS %dU\n", runtimeabi.FNVOffsetBasis))
	buf.WriteString(fmt.Sprintf("#define FERRET_FNV_PRIME %dU\n", runtimeabi.FNVPrime))
	buf.WriteString("\n// Big integer/float specs.\n")
	buf.WriteString("#define FERRET_INT_WIDTHS(X) \\\n")
	for i, bits := range intWidths {
		lineEnd := " \\\n"
		if i == len(intWidths)-1 {
			lineEnd = "\n"
		}
		buf.WriteString(fmt.Sprintf("    X(%d)%s", bits, lineEnd))
	}
	buf.WriteString("#define FERRET_FLOAT_SPECS(X) \\\n")
	for i, spec := range floatSpecs {
		lineEnd := " \\\n"
		if i == len(floatSpecs)-1 {
			lineEnd = "\n"
		}
		buf.WriteString(fmt.Sprintf("    X(%d, %d, %d, %d, %d, %d)%s",
			spec.Bits,
			spec.Words,
			spec.FracBits,
			spec.ExpBits,
			spec.ExpBias,
			spec.DecimalDigits,
			lineEnd,
		))
	}
	buf.WriteString(fmt.Sprintf("#define FERRET_SOFT_EXTRA_BITS %d\n", runtimeabi.SoftExtraBits))
	buf.WriteString("\n#endif // FERRET_ABI_CONSTANTS_H\n")
	return os.WriteFile(path, buf.Bytes(), 0o644)
}

func writeGo(path string, primitiveKinds []string, values map[string]uint32) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by scripts/gen_abi_constants.go; DO NOT EDIT.\n")
	buf.WriteString("package abi\n\n")
	buf.WriteString("import \"compiler/internal/types\"\n\n")
	buf.WriteString("const (\n")
	for _, name := range primitiveKinds {
		buf.WriteString(fmt.Sprintf("\tTypeKind%s uint32 = %d\n", goName(name), values[name]))
	}
	for _, name := range nonPrimitiveKinds {
		buf.WriteString(fmt.Sprintf("\tTypeKind%s uint32 = %d\n", goName(name), values[name]))
	}
	buf.WriteString("\tTypeKindPrimitiveEnd uint32 = TypeKindPointer\n")
	buf.WriteString(")\n\n")

	buf.WriteString("var PrimitiveTypeOrder = []types.TYPE_NAME{\n")
	for _, name := range types.PrimitiveTypeNames {
		buf.WriteString(fmt.Sprintf("\ttypes.TYPE_%s,\n", abiKindName(name)))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var PrimitiveKindByName = map[types.TYPE_NAME]uint32{\n")
	for _, name := range types.PrimitiveTypeNames {
		kindName := abiKindName(name)
		buf.WriteString(fmt.Sprintf("\ttypes.TYPE_%s: TypeKind%s,\n", kindName, goName(kindName)))
	}
	buf.WriteString("}\n")

	return os.WriteFile(path, buf.Bytes(), 0o644)
}

func writeTS(path string, primitiveKinds []string, values map[string]uint32, mapKeyKinds []string, intWidths []int, floatSpecs []runtimeabi.FloatSpec) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by scripts/gen_abi_constants.go; DO NOT EDIT.\n")
	for _, name := range primitiveKinds {
		buf.WriteString(fmt.Sprintf("export const TYPE_KIND_%s = %d;\n", name, values[name]))
	}
	for _, name := range nonPrimitiveKinds {
		buf.WriteString(fmt.Sprintf("export const TYPE_KIND_%s = %d;\n", name, values[name]))
	}
	buf.WriteString("\n// WASM type descriptor layout (packed u32 fields).\n")
	buf.WriteString(fmt.Sprintf("export const TYPE_DESC_KIND_OFFSET = %d;\n", runtimeabi.TypeDescKindOffset))
	buf.WriteString(fmt.Sprintf("export const TYPE_DESC_SIZE_OFFSET = %d;\n", runtimeabi.TypeDescSizeOffset))
	buf.WriteString(fmt.Sprintf("export const TYPE_DESC_INFO1_OFFSET = %d;\n", runtimeabi.TypeDescInfo1Offset))
	buf.WriteString(fmt.Sprintf("export const TYPE_DESC_INFO2_OFFSET = %d;\n", runtimeabi.TypeDescInfo2Offset))
	buf.WriteString(fmt.Sprintf("export const TYPE_DESC_SIZE = %d;\n", runtimeabi.TypeDescSizeBytes))
	buf.WriteString(fmt.Sprintf("export const FIELD_INFO_OFFSET_OFFSET = %d;\n", runtimeabi.FieldInfoOffsetOffset))
	buf.WriteString(fmt.Sprintf("export const FIELD_INFO_TYPE_OFFSET = %d;\n", runtimeabi.FieldInfoTypeOffset))
	buf.WriteString(fmt.Sprintf("export const FIELD_INFO_SIZE = %d;\n", runtimeabi.FieldInfoSizeBytes))
	buf.WriteString("\n// WASM runtime layout constants.\n")
	buf.WriteString(fmt.Sprintf("export const ARRAY_DATA_OFFSET = %d;\n", runtimeabi.ArrayDataOffset))
	buf.WriteString(fmt.Sprintf("export const ARRAY_LEN_OFFSET = %d;\n", runtimeabi.ArrayLenOffset))
	buf.WriteString(fmt.Sprintf("export const ARRAY_CAP_OFFSET = %d;\n", runtimeabi.ArrayCapOffset))
	buf.WriteString(fmt.Sprintf("export const ARRAY_ELEM_SIZE_OFFSET = %d;\n", runtimeabi.ArrayElemSizeOffset))
	buf.WriteString(fmt.Sprintf("export const ARRAY_ELEM_TYPE_OFFSET = %d;\n", runtimeabi.ArrayElemTypeOffset))
	buf.WriteString(fmt.Sprintf("export const ARRAY_HEADER_SIZE = %d;\n", runtimeabi.ArrayHeaderSize))
	buf.WriteString(fmt.Sprintf("export const SLICE_DATA_OFFSET = %d;\n", runtimeabi.SliceDataOffset))
	buf.WriteString(fmt.Sprintf("export const SLICE_LEN_OFFSET = %d;\n", runtimeabi.SliceLenOffset))
	buf.WriteString(fmt.Sprintf("export const SLICE_CAP_OFFSET = %d;\n", runtimeabi.SliceCapOffset))
	buf.WriteString(fmt.Sprintf("export const SLICE_ELEM_SIZE_OFFSET = %d;\n", runtimeabi.SliceElemSizeOffset))
	buf.WriteString(fmt.Sprintf("export const SLICE_ELEM_TYPE_OFFSET = %d;\n", runtimeabi.SliceElemTypeOffset))
	buf.WriteString(fmt.Sprintf("export const SLICE_HEADER_SIZE = %d;\n", runtimeabi.SliceHeaderSize))
	buf.WriteString(fmt.Sprintf("export const INTERFACE_DATA_OFFSET = %d;\n", runtimeabi.InterfaceDataOffset))
	buf.WriteString(fmt.Sprintf("export const INTERFACE_EXTRA_OFFSET = %d;\n", runtimeabi.InterfaceExtraOffset))
	buf.WriteString(fmt.Sprintf("export const INTERFACE_SIZE = %d;\n", runtimeabi.InterfaceSize))
	buf.WriteString(fmt.Sprintf("export const UNION_TAG_SIZE = %d;\n", runtimeabi.UnionTagSize))
	buf.WriteString(fmt.Sprintf("export const UNION_PTR_OFFSET = %d;\n", runtimeabi.UnionPtrOffset))
	buf.WriteString(fmt.Sprintf("export const MAP_HANDLE_SIZE = %d;\n", runtimeabi.MapHandleSize))
	buf.WriteString("\n// Hash constants.\n")
	buf.WriteString(fmt.Sprintf("export const MAP_HASH_SEED = %d;\n", runtimeabi.MapHashSeed))
	buf.WriteString(fmt.Sprintf("export const FNV_OFFSET_BASIS = %d;\n", runtimeabi.FNVOffsetBasis))
	buf.WriteString(fmt.Sprintf("export const FNV_PRIME = %d;\n", runtimeabi.FNVPrime))
	buf.WriteString("\n// Big integer/float specs.\n")
	buf.WriteString("export const BIG_INT_WIDTHS = [\n")
	for _, bits := range intWidths {
		buf.WriteString(fmt.Sprintf("  %d,\n", bits))
	}
	buf.WriteString("] as const;\n")
	buf.WriteString("export type BigIntWidth = (typeof BIG_INT_WIDTHS)[number];\n")
	buf.WriteString("export const BIG_FLOAT_SPECS = [\n")
	for _, spec := range floatSpecs {
		buf.WriteString(fmt.Sprintf("  { bits: %d, words: %d, fracBits: %dn, expBits: %dn, expBias: %d, decimalDig: %d },\n",
			spec.Bits,
			spec.Words,
			spec.FracBits,
			spec.ExpBits,
			spec.ExpBias,
			spec.DecimalDigits,
		))
	}
	buf.WriteString("] as const;\n")
	buf.WriteString("export type BigFloatSpec = (typeof BIG_FLOAT_SPECS)[number];\n")
	buf.WriteString(fmt.Sprintf("export const SOFT_EXTRA_BITS = %dn;\n", runtimeabi.SoftExtraBits))
	buf.WriteString("\n// Core WASM import names.\n")
	for _, name := range runtimeabi.WasmCoreImportNames {
		buf.WriteString(fmt.Sprintf("export const %s = %q;\n", wasmImportConstName(name), name))
	}
	buf.WriteString("\nexport const WASM_CORE_IMPORTS = [\n")
	for _, name := range runtimeabi.WasmCoreImportNames {
		buf.WriteString(fmt.Sprintf("  %s,\n", wasmImportConstName(name)))
	}
	buf.WriteString("] as const;\n")
	buf.WriteString("export type WasmCoreImportName = (typeof WASM_CORE_IMPORTS)[number];\n")
	buf.WriteString("\nexport const MAP_KEY_KINDS = [\n")
	for _, kind := range mapKeyKinds {
		buf.WriteString(fmt.Sprintf("  %q,\n", kind))
	}
	buf.WriteString("] as const;\n")
	buf.WriteString("export type FerretMapKeyKind = (typeof MAP_KEY_KINDS)[number];\n")
	return os.WriteFile(path, buf.Bytes(), 0o644)
}

func writePrimitiveTypesHeader(path string, specs []runtimeabi.PrimitiveSpec) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by scripts/gen_abi_constants.go; DO NOT EDIT.\n")
	buf.WriteString("#ifndef FERRET_PRIMITIVE_TYPES_H\n")
	buf.WriteString("#define FERRET_PRIMITIVE_TYPES_H\n\n")
	buf.WriteString("// Primitive types in Printable union order (ferret_libs/std/io.fer).\n")
	buf.WriteString("#define FERRET_PRIMITIVE_TYPES(X) \\\n")
	for i, spec := range specs {
		lineEnd := " \\\n"
		if i == len(specs)-1 {
			lineEnd = "\n"
		}
		buf.WriteString(fmt.Sprintf("    X(%s, %s, %s, %s, %d)%s",
			abiKindName(spec.Name),
			spec.Name,
			spec.CType,
			spec.Category,
			spec.Bits,
			lineEnd,
		))
	}
	buf.WriteString("\n#endif // FERRET_PRIMITIVE_TYPES_H\n")
	return os.WriteFile(path, buf.Bytes(), 0o644)
}

func validatePrimitiveSpecs(specs []runtimeabi.PrimitiveSpec) error {
	if len(specs) != len(types.PrimitiveTypeNames) {
		return fmt.Errorf("primitive spec count %d does not match builtin list %d", len(specs), len(types.PrimitiveTypeNames))
	}
	for i, name := range types.PrimitiveTypeNames {
		if specs[i].Name != name {
			return fmt.Errorf("primitive spec order mismatch at %d: %s vs %s", i, specs[i].Name, name)
		}
	}
	return nil
}

func goName(name string) string {
	parts := strings.Split(strings.ToLower(name), "_")
	for i, part := range parts {
		if part == "" {
			continue
		}
		r := []rune(part)
		r[0] = []rune(strings.ToUpper(string(r[0])))[0]
		parts[i] = string(r)
	}
	return strings.Join(parts, "")
}

func wasmImportConstName(name string) string {
	var b strings.Builder
	for _, r := range name {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
			continue
		}
		b.WriteRune('_')
	}
	out := strings.ToUpper(b.String())
	return "WASM_IMPORT_" + out
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
