// Code generated by scripts/gen_abi_constants.go; DO NOT EDIT.
package abi

import "compiler/internal/types"

const (
	TypeKindI8 uint32 = 0
	TypeKindI16 uint32 = 1
	TypeKindI32 uint32 = 2
	TypeKindI64 uint32 = 3
	TypeKindI128 uint32 = 4
	TypeKindI256 uint32 = 5
	TypeKindU8 uint32 = 6
	TypeKindU16 uint32 = 7
	TypeKindU32 uint32 = 8
	TypeKindU64 uint32 = 9
	TypeKindU128 uint32 = 10
	TypeKindU256 uint32 = 11
	TypeKindF32 uint32 = 12
	TypeKindF64 uint32 = 13
	TypeKindF128 uint32 = 14
	TypeKindF256 uint32 = 15
	TypeKindString uint32 = 16
	TypeKindByte uint32 = 17
	TypeKindChar uint32 = 18
	TypeKindBool uint32 = 19
	TypeKindPointer uint32 = 20
	TypeKindStruct uint32 = 21
	TypeKindArray uint32 = 22
	TypeKindSlice uint32 = 23
	TypeKindMap uint32 = 24
	TypeKindFunction uint32 = 25
	TypeKindInterface uint32 = 26
	TypeKindPrimitiveEnd uint32 = TypeKindPointer
)

var PrimitiveTypeOrder = []types.TYPE_NAME{
	types.TYPE_I8,
	types.TYPE_I16,
	types.TYPE_I32,
	types.TYPE_I64,
	types.TYPE_I128,
	types.TYPE_I256,
	types.TYPE_U8,
	types.TYPE_U16,
	types.TYPE_U32,
	types.TYPE_U64,
	types.TYPE_U128,
	types.TYPE_U256,
	types.TYPE_F32,
	types.TYPE_F64,
	types.TYPE_F128,
	types.TYPE_F256,
	types.TYPE_STRING,
	types.TYPE_BYTE,
	types.TYPE_CHAR,
	types.TYPE_BOOL,
}

var PrimitiveKindByName = map[types.TYPE_NAME]uint32{
	types.TYPE_I8: TypeKindI8,
	types.TYPE_I16: TypeKindI16,
	types.TYPE_I32: TypeKindI32,
	types.TYPE_I64: TypeKindI64,
	types.TYPE_I128: TypeKindI128,
	types.TYPE_I256: TypeKindI256,
	types.TYPE_U8: TypeKindU8,
	types.TYPE_U16: TypeKindU16,
	types.TYPE_U32: TypeKindU32,
	types.TYPE_U64: TypeKindU64,
	types.TYPE_U128: TypeKindU128,
	types.TYPE_U256: TypeKindU256,
	types.TYPE_F32: TypeKindF32,
	types.TYPE_F64: TypeKindF64,
	types.TYPE_F128: TypeKindF128,
	types.TYPE_F256: TypeKindF256,
	types.TYPE_STRING: TypeKindString,
	types.TYPE_BYTE: TypeKindByte,
	types.TYPE_CHAR: TypeKindChar,
	types.TYPE_BOOL: TypeKindBool,
}
